name: Steganography post-push
on:
  push:
      branches:
        - main
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Wav LSB
      run: cd tests && python3 TestWavLSB.py
    - name: Video Parse
      run: cd tests && python3 TestVideoParse.py
