name: Steganography post-push
on:
  push:
      branches:
        - main
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Install python deps
      run: pip install -r requirements.txt
    - name: Install utils
      run: sudo apt install ffmpeg
    - name: LSB Frame
      run: cd src/tests && python3 TestLSBFrame.py
    - name: LSB Png
      run: cd src/tests && python3 TestLSBPng.py
    - name: LSB Wav
      run: cd src/tests && python3 TestLSBWav.py
    - name: Video Parse
      run: cd src/tests && python3 TestVideoParse.py
